---
title: "活用資料框 - 隨堂練習"
author: "Yao-Jen Kuo"
date: "`r Sys.Date()`"
output: 
  html_document:
    self_contained: false
---

```{r, include=FALSE}
tutorial::go_interactive()
```

## 轉換變數類型

練習把一個文字（character）轉換成 Date 格式。

```{r ex="char_transform", type="sample-code"}
# Create the character
boston_marathon_2016 <- "2016-04-18"

# Check the variable type using `class()`


# Using as.Date() to transform the character and re-assign it to another variable `bm_2016_date`
bm_2016_date <- 

# Check the newly created variable type using `class()`

```

```{r ex="char_transform", type="solution"}
# Create the character
boston_marathon_2016 <- "2016-04-18"

# Check the variable type using `class()`
class(boston_marathon_2016)

# Using as.Date() to transform the character and re-assign it to another variable `bm_2016_date`
bm_2016_date <- as.Date(boston_marathon_2016)

# Check the newly created variable type using `class()`
class(bm_2016_date)
```

```{r ex="char_transform", type="sct"}
test_output_contains("class(boston_marathon_2016)", incorrect_msg = "Did you use `class()` on boston_marathon_2016?")
test_object("bm_2016_date", incorrect_msg = "Did you transform the character variable to date correctly?")
test_output_contains("class(bm_2016_date)", incorrect_msg = "Did you use `class()` on bm_2016_date?")
```

## 聯結資料框

練習將兩個資料框 `order_data` 與 `customer_data` 進行內部合併。

```{r ex="merge_dfs", type="pre-exercise-code"}
order_data <- read.csv("http://storage.googleapis.com/r_rookies/merge_1.csv")
customer_data <- read.csv("http://storage.googleapis.com/r_rookies/merge_2.csv")
```

```{r ex="merge_dfs", type="sample-code"}
# Print order_data which was loaded previously


# Print customer_data which was loaded previously


# Merge these 2 data frames using their common variable: CustomerID and assign to a new data frame: merged_data
merged_data <- merge(___, ___)

# Print merged_data to the console

```

```{r ex="merge_dfs", type="solution"}
# Print order_data which was loaded previously
order_data

# Print customer_data which was loaded previously
customer_data

# Merge these 2 data frames using their common variable: CustomerID and assign to a new data frame: merged_data
merged_data <- merge(order_data, customer_data)

# Print merged_data to the console
merged_data
```

```{r ex="merge_dfs", type="sct"}
test_output_contains("order_data", incorrect_msg="Did you print out `order_data` to the console?")
test_output_contains("customer_data", incorrect_msg="Did you print out `customer_data` to the console?")
test_object("merged_data", incorrect_msg="Did you merge the data correctly?")
test_output_contains("merged_data", incorrect_msg="Did you print out `merged_data` to the console?")
```