---
title: "自訂函數 - 隨堂練習"
author: "Yao-Jen Kuo"
date: "`r Sys.Date()`"
output: 
  html_document:
    self_contained: false
---

```{r, include=FALSE}
tutorial::go_interactive()
```

## 練習實作 R 既有的函數

練習實作 R 既有的函數 `max()`，它可以回傳一組向量中的最大值。

```{r ex="max_function", type="sample-code"}
# Declare my.max()
my.max <- function(input_vector) {
  # Use sort() to sort input_vector with descending order and assign to sorted_vector
  sorted_vector <- sort(input_vector, decreasing = ___)
  # Return the first scalar of sorted_vector
  return(___)
}

# Generate a vector
my_vector <- round(runif(10) * 100)

# Print my_vector out


# Call my.max() on my_vector

```

```{r ex="max_function", type="solution"}
# Declare my.max()
my.max <- function(input_vector) {
  # Use sort() to sort input_vector with descending order and assign to sorted_vector
  sorted_vector <- sort(input_vector, decreasing = TRUE)
  # Return the first scalar of sorted_vector
  return(sorted_vector[1])
}

# Generate a vector
my_vector <- round(runif(10) * 100)

# Print my_vector out
my_vector

# Call my.max() on my_vector
my.max(my_vector)
```

```{r ex="max_function", type="sct"}
test_function_definition("my.max", undefined_msg = "Did you correctly declare the function `my.max()`?")
test_output_contains("my_vector", incorrect_msg = "Did you print `my_vector` out?")
test_output_contains("my.max(my_vector)", incorrect_msg = "Did you call `my.max()` on `my_vector` correctly?")
```